#!/bin/bash

cwd=~/programming/dotfiles
compton_path=.config/compton/compton.conf
gtk2_path=.config/gtk-2.0/.gtkrc-2.0
gtk3_path=.config/gtk-3.0/settings.ini
i3_path=.config/i3/config
polybar_path=.config/polybar/config
rofi_config_path=.config/rofi/config.rasi
rofi_theme_path=.config/rofi/mytheme.rasi
terminator_path=.config/terminator/config

cp ~/$compton_path $cwd/$compton_path
cp ~/$gtk2_path $cwd/$gtk2_path
cp ~/$gtk3_path $cwd/$gtk3_path
cp ~/$i3_path $cwd/$i3_path
cp ~/$polybar_path $cwd/$polybar_path
cp ~/$rofi_config_path $cwd/$rofi_config_path
cp ~/$rofi_theme_path $cwd/$rofi_theme_path
cp ~/$terminator_path $cwd/$terminator_path
